User.create(name: "Monica", email: "monica@friends.com", password: "password")
User.create(name: "Joey", email: "joey@friends.com", password: "password")
User.create(name: "Chandler", email: "chandler@friends.com", password: "password")
User.create(name: "Ross", email: "ross@friends.com", password: "password")

Category.create(name: "Fiction")
Category.create(name: "Non-Fiction")
Category.create(name: "Fantasy")
Category.create(name: "Romance")
Category.create(name: "Science Fiction")
Category.create(name: "Mystery")

Book.create(title: "End of the World Running Club", author: "Some Guy", category_id: 1)
Book.create(title: "Harry Potter" , author: "J.K. Rowling", category_id: 3)
Book.create(title: "Once and Future King", author: "T.H. White", category_id: 3)
Book.create(title: "Four Tendancies", author: "Gretchen Rubin", category_id: 2)
Book.create(title: "Weaving the Web", author: "Tim Lee", category_id: 4)

BookListItem.create(note: "Might be a good one", library_link: "https://catalogplus.libraryweb.org/?section=resource&resourceid=17385564&currentIndex=0&view=allCopiesDetailsTab", user_id: 1, book_id: 2)
BookListItem.create(note: "Looks Interesting", library_link: "https://catalogplus.libraryweb.org/?section=resource&resourceid=17385564&currentIndex=0&view=allCopiesDetailsTab", user_id: 2, book_id: 2)
BookListItem.create(note: "recommended by Mike", library_link: "https://catalogplus.libraryweb.org/?section=resource&resourceid=20639495&currentIndex=0&view=allCopiesDetailsTab", user_id: 2, book_id: 3)
BookListItem.create(note: "Should read for work", library_link: "https://catalogplus.libraryweb.org/?section=resource&resourceid=1109228200&currentIndex=0&view=allCopiesDetailsTab", user_id: 4, book_id: 4)
